name: test
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "OK"
      - name: Checkout
        uses: actions/checkout@v6.1.0
      - name: List files in repository
        run: |
          echo "The repository ${{github.repository}} contains the following files:"
          tree
          
